version: "3.8"
services:
  db:
    image:
    volumes:
      - ./tmp/db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    image: unagiya/rails-study:1.0.0
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    expose: ["3000"]
    ports: ["3000:3000"]
    user: root
    working_dir: /app
